### ISSUE TITLE
Components blocking utilities

### ISSUE THREAD

**Issue by atav1k** [atav1k/fortune#3]
<img width="1119" alt="screen shot 2018-04-05 at 9 24 38 am" src="https://user-images.githubusercontent.com/1778311/38378651-3acba394-38b3-11e8-9b9a-40a3b0b16f50.png">
Adding a utility class (eg radius-3) to a component (button) does not modify the component.

**Comment by atav1k** [comment]
Seems the simplest ways to solve this are either add write utility classes like `body .radius-3 { prop }` or just change the order of fortune.css to have components before utilities.

**Comment by chasestarr** [comment]
you mentioned this issue was resolved?

**Comment by atav1k** [comment]
The solution is there, but it isn't resolved for components that have higher specificity in their CSS, eg. Tabs

https://github.com/atav1k/fortune/blob/b864f0a61f917acd36fa733ddeaa51f318256b18/src/tab.css#L5

**Comment by atav1k** [comment]
Simple hack to raise specificity is .class.class instead of !important
